services:
# ==========================================================
# DATABASE - MARIADB
# ==========================================================

  database:

   #MariaDB đúng version máy hiện tại của bn
   image: mariadb:12.3.2

   #Tên container
   container_name: systemanagercv-db # Đặt tên cho chiếc máy ảo DB này để dễ quản lý

   # ========================================================
   # DATABASE CONFIGURATION (Cấu hình DB)
   # ========================================================
   environment:  # THIẾT LẬP BIẾN MÔI TRƯỜNG (Cấu hình tài khoản DB)

     # Mật khẩu tài khoản root
     MARIADB_ROOT_PASSWORD: 123456

     #Tự động tạo database này khi container chạy lần đầu
     MARIADB_DATABASE: systemcv_db

   ports:
      # Máy Windows : Docker container
      #
      # HeidiSQL sẽ kết nối:
      # localhost:3307
      #
      # MariaDB bên trong container vẫn chạy:
      # 3306
     - "3307:3306"                              # CẦU NỐI CỔNG MẠNG: Ép cổng 3306 mặc định bên trong máy ảo
                                                # thông ra cổng 3307 ngoài máy thật của bạn.
                                                # (Nhờ dòng này, bạn mở HeidiSQL gõ Port 3307 là kết nối được vào máy ảo).

   volumes:
      # Lưu dữ liệu MariaDB
     - mariadb_data:/var/lib/mysql

   restart: unless-stopped

   # ==========================================================
   # SPRING BOOT APPLICATION
   # ==========================================================

  app:

   build:
     context: .
     dockerfile: Dockerfile

   container_name: systemanagercv-app

   ports:
     # Truy cập Spring Boot:
     # http://localhost:8080
     - "8080:8080"

   depends_on:
     - database

   restart: unless-stopped

  # ==========================================================
  # DOCKER VOLUME
  # ==========================================================

volumes:

 # Volume lưu dữ liệu MariaDB
 mariadb_data: