services:

  # ==========================================================
  # DATABASE - MARIADB
  # ==========================================================

  database:

    # MariaDB version
    image: mariadb:12.3.2

    # Container name
    container_name: systemanagercv-db

    # ========================================================
    # DATABASE CONFIGURATION
    # ========================================================

    environment:

      # Root password
      MARIADB_ROOT_PASSWORD: 123456

      # Database tự động tạo
      MARIADB_DATABASE: systemcv_db

    ports:
      # Windows : Docker
      #
      # HeidiSQL:
      # localhost:3307
      #
      # MariaDB bên trong container:
      # 3306

      - "3307:3306"

    volumes:
      # Persistent database data

      - mariadb_data:/var/lib/mysql

    restart: unless-stopped

    # ========================================================
    # HEALTH CHECK
    # ========================================================

    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]

      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  # ==========================================================
  # SPRING BOOT APPLICATION
  # ==========================================================

  app:

    # Build image từ Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Container name
    container_name: systemanagercv-app

    ports:
      # Windows:Container
      - "8080:8080"

    # ========================================================
    # ENVIRONMENT VARIABLES
    # ========================================================

    environment:

      # ------------------------------------------------------
      # DATABASE
      # ------------------------------------------------------

      DB_URL: jdbc:mariadb://database:3306/systemcv_db?useSSL=false
      DB_USERNAME: root
      DB_PASSWORD: 123456

      # ------------------------------------------------------
      # JWT
      # ------------------------------------------------------

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-3600000}

    # ========================================================
    # DATABASE DEPENDENCY
    # ========================================================

    depends_on:

      database:
        condition: service_healthy

    restart: unless-stopped


# ==========================================================
# DOCKER VOLUMES
# ==========================================================

volumes:

  mariadb_data: