# =====================================================
# APPLICATION
# =====================================================

spring.application.name=systemanagercv


# =====================================================
# DATABASE - MARIADB
# =====================================================

spring.datasource.url=jdbc:mariadb://localhost:3306/systemcv_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Hibernate KHÔNG được tự ý tạo/sửa bảng
# Liquibase sẽ chịu trách nhiệm quản lý database
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true


# =====================================================
# LIQUIBASE
# =====================================================

spring.liquibase.enabled=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#thêm tạm để check lỗi Liquibase
# =====================================================
# LIQUIBASE DEBUG
# =====================================================

logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG
debug=true

#                    ┌─────────────────┐
#                    │    Spring Boot  │
#                    └────────┬────────┘
#                             │
#              ┌──────────────┴──────────────┐
#              │                             │
#              ▼                             ▼
#        ┌───────────┐                 ┌───────────┐
#        │ Hibernate │                 │ Liquibase │
#        └─────┬─────┘                 └─────┬─────┘
#              │                             │
#              │ validate                    │ migration
#              │                             │
#              └──────────────┬──────────────┘
#                             ▼
#                    ┌─────────────────┐
#                    │   systemcv_db   │
#                    └─────────────────┘