# =====================================================
# APPLICATION
# =====================================================

spring.application.name=systemanagercv

# Load environment variables from .env
spring.config.import=optional:file:.env[.properties]

# =====================================================
# DATABASE - MARIADB
# =====================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# =====================================================
# LIQUIBASE
# =====================================================

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# =====================================================
# LIQUIBASE DEBUG
# =====================================================

logging.level.liquibase=DEBUG
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG

debug=true